######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 14 17:45:04 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += photopreviewdlg.h
SOURCES += main.cpp photopreviewdlg.cpp
RESOURCES += photo_prev.qrc
